spring:
  application:
    name: tg-provider
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/tg
      username: wusi
      password: 666666
  redis:
#      cluster:
#        nodes:
#            - 172.18.12.125:6379
#            - 172.18.12.126:6379
#            - 172.18.12.128:6379
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      #password:
      # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0
  profiles:
    active: dev
  batch:
    initializer:
      enabled: true
    job:
      enabled: false
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update

server:
  port: 2222

mybatis:
#    type-aliases-package: top.treegrowth.model.entity
    mapper-locations: classpath:/mapper/*.xml

pagehelper:
    helperDialect: postgresql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
