top:
  treegrowth:
    sms:
      app-key: 23619128
      app-secret: 6da78ba64760f7d1648e196b58b7e18a
      sign-name: 梯局
      template-id: SMS_44440450

#logging:
#  level:
#    root: debug
#debug: true